image:
  name: docker/compose:1.24.0
  entrypoint: ['/bin/sh', '-c']

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - ./setup.sh --non-interactive --prune --detach

test_app:
  stage: test
  dependencies:
    - build
  script:
    - docker-compose run --rm app python manage.py test

test_static:
  stage: test
  dependencies:
    - build
  script:
    - docker-compose run --rm static npm run test
