image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - ./setup.sh --non-interactive --prune

test:
  stage: test
  dependencies:
    - build
  script:
    - docker-compose up --detach
    - docker-compose run --rm app python manage.py test
    - docker-compose run --rm app npm run test
    - docker-compose down
