image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

after_script:
  - docker-compose down

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - ./setup.sh --non-interactive --prune --detach

test_app:
  stage: test
  dependencies:
    - build
  script:
    - docker-compose exec app python manage.py test

test_static:
  stage: test
  dependencies:
    - build
  script:
    - docker-compose exec static npm run test
