version: '3.4'

services:
  db:
    env_file: .env
    expose:
      - 5432
    image: postgres:11.3-alpine
    restart: always
    tty: true
    volumes:
      - database:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: app
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
      - "8080:8080"
    restart: always
    tty: true
    volumes:
      - dist:/app/dist
      - media:/app/media
      - ./developerportal:/app/developerportal
      - ./src:/app/src

  reload:
    build:
      context: .
      target: app
    command: python manage.py livereload --host=0.0.0.0
    depends_on:
      - app
    env_file: .env
    ports:
      - "35729:35729"
    restart: always
    tty: true
    volumes:
      - dist:/app/dist
      - media:/app/media
      - ./developerportal:/app/developerportal
      - ./src:/app/src

  static:
    build:
      context: .
      target: static
    command: npm run watch
    restart: always
    tty: true
    volumes:
      - dist:/app/dist
      - ./src:/app/src

volumes:
  database:
  dist:
  media:
