version: '3'

services:
  db:
    env_file: .env
    expose:
      - 5432
    image: postgres:9.6
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - db
    env_file: .env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./src:/app/src
      - ./developerportal:/app/developerportal
