version: '3'

services:
  db:
    env_file: .env
    expose:
      - 5432
    image: postgres:11.3
    restart: always
    tty: true
    volumes:
      - database:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    depends_on:
      - db
    env_file: .env
    ports:
      - 8000:8000
    restart: always
    tty: true
    volumes:
      - dist:/app/dist
      - ./developerportal:/app/developerportal
      - ./src:/app/src

  static:
    build:
      context: .
      dockerfile: ./docker/static.Dockerfile
    command: npm run watch
    restart: always
    tty: true
    volumes:
      - dist:/app/dist
      - ./src:/app/src

volumes:
  database:
  dist:
