version: '3'

services:
  db:
    tty: true
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - '5432'

  app:
    tty: true
    command: npm start
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - './src:/app/src'
      - './developerportal:/app/developerportal'
